#!/usr/bin/env bash
# Backup the original /etc/hosts file
cp /etc/hosts /etc/hosts.bak

# Add the new entries to /etc/hosts
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
    } | tee /etc/hosts > /dev/null
